#启动基础服务 数据库、缓存、消息中间件

version: '3'
services:
  #  数据库
  mysql:
    container_name: pig-compose-mysql
    image: registry.cn-hangzhou.aliyuncs.com/sherry/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    volumes:
    - /Users/zhangliuning/Volumes/mysql/data:/var/lib/mysql
    restart: always
    ports:
    - 3306:3306
  #   Redis
  redis:
    container_name: pig-compose-redis
    image: registry.cn-hangzhou.aliyuncs.com/sherry/redis:3.2.9
    ports:
    - 6379:6379
  #      RabbitMQ
  rabbitmq:
    container_name: pig-compose-rabbitmq
    image: registry.cn-hangzhou.aliyuncs.com/sherry/rabbitmq:3.7-management
    hostname: rabbitmqhost
    environment:
      RABBITMQ_DEFAULT_USER: pig
      RABBITMQ_DEFAULT_PASS: pig
    volumes:
    - /Users/zhangliuning/Volumes/rabbitmq:/var/rabbitmq/lib
    ports:
    - 15672:15672
    - 5672:5672